In [31]:
import numpy as np
import os
from PIL import Image

In [32]:
# path to the image directory
dir_data  = "img"
 
# setting image shape to 32x32
img_shape = (32, 32, 3)
 
# listing out all file names
nm_imgs   = np.sort(os.listdir(dir_data))

In [34]:
X_train = []
for file in nm_imgs:
    img = Image.open(dir_data + '/' + file)
    img = img.convert('RGB')
    img = img.resize((32,32))
    img = np.asarray(img)/255
    X_train.append(img)
 
X_train = np.array(X_train)

In [35]:
X_train.shape

(988, 32, 32, 3)

In [37]:
from numpy import asarray
from numpy import savez_compressed
 
# save to npy file
savez_compressed('images_32x32.npz', X_train)

In [38]:
# load dict of arrays
dict_data = np.load('images_32x32.npz')
 
# extract the first array
data = dict_data['arr_0']
 
# print the array
print(data)

[[[[0.07843137 0.08627451 0.06666667]
   [0.06666667 0.0745098  0.05882353]
   [0.05882353 0.06666667 0.05882353]
   ...
   [0.07843137 0.08235294 0.0627451 ]
   [0.0627451  0.0627451  0.05098039]
   [0.04705882 0.04705882 0.03921569]]

  [[0.10980392 0.10980392 0.09019608]
   [0.10196078 0.10588235 0.08627451]
   [0.09803922 0.10196078 0.08235294]
   ...
   [0.11372549 0.11372549 0.09803922]
   [0.09803922 0.09803922 0.08627451]
   [0.0745098  0.0745098  0.06666667]]

  [[0.06666667 0.07058824 0.06666667]
   [0.0745098  0.07843137 0.06666667]
   [0.09411765 0.10196078 0.07843137]
   ...
   [0.14117647 0.14117647 0.1254902 ]
   [0.12941176 0.12941176 0.12156863]
   [0.10980392 0.10588235 0.09803922]]

  ...

  [[0.06666667 0.09411765 0.09019608]
   [0.09803922 0.1254902  0.10196078]
   [0.0745098  0.09803922 0.09411765]
   ...
   [0.09803922 0.1372549  0.15294118]
   [0.10588235 0.15294118 0.16470588]
   [0.10980392 0.15686275 0.16862745]]

  [[0.06666667 0.08627451 0.09411765]
   [0.0