In [1]:
import numpy as np
import os
from PIL import Image

In [2]:
# path to the image directory
dir_data  = "img"
 
# setting image shape to 32x32
img_shape = (100, 100, 3)
 
# listing out all file names
nm_imgs   = np.sort(os.listdir(dir_data))

In [3]:
X_train = []
for file in nm_imgs:
    img = Image.open(dir_data + '/' + file)
    img = img.convert('RGB')
    img = img.resize((100,100))
    img = np.asarray(img)/255
    X_train.append(img)
 
X_train = np.array(X_train)

In [4]:
X_train.shape

(988, 100, 100, 3)

In [5]:
from numpy import asarray
from numpy import savez_compressed
 
# save to npy file
savez_compressed('images_100x100.npz', X_train)

In [6]:
# load dict of arrays
dict_data = np.load('images_100x100.npz')
 
# extract the first array
data = dict_data['arr_0']
 
# print the array
print(data)

[[[[0.06666667 0.0745098  0.07058824]
   [0.05490196 0.0627451  0.05882353]
   [0.05490196 0.0627451  0.05882353]
   ...
   [0.05490196 0.05490196 0.04705882]
   [0.05098039 0.05098039 0.04313725]
   [0.04705882 0.04705882 0.03921569]]

  [[0.08235294 0.09019608 0.0745098 ]
   [0.05882353 0.06666667 0.05098039]
   [0.05098039 0.05882353 0.04313725]
   ...
   [0.04705882 0.04705882 0.03921569]
   [0.03921569 0.03921569 0.03137255]
   [0.03529412 0.03529412 0.02745098]]

  [[0.11764706 0.12156863 0.10196078]
   [0.09803922 0.10196078 0.07843137]
   [0.08235294 0.09019608 0.06666667]
   ...
   [0.05490196 0.05490196 0.04705882]
   [0.04705882 0.04705882 0.03921569]
   [0.04313725 0.04313725 0.03529412]]

  ...

  [[0.08627451 0.11764706 0.10980392]
   [0.17254902 0.19607843 0.18823529]
   [0.20784314 0.22352941 0.21568627]
   ...
   [0.04313725 0.06666667 0.10588235]
   [0.02745098 0.0627451  0.08235294]
   [0.0627451  0.09019608 0.1254902 ]]

  [[0.08627451 0.11372549 0.10980392]
   [0.0